### ISSUE TITLE
 invalid int value: 'torch'

### ISSUE THREAD

**Issue by ajr82** [andreped/fast-stain-normalization#1]
Hi Andre, 

I am using Python 3.9.7 on Windows 10 and have installed all requirements (from requirements.txt). 

However when I run the following: 
_fastStainNorm --ref /Ref/001.tif --img /Images --out /Imagesnorm_

/Images is where I have my images to normalize and /Imagesnorm is the output folder. 
/Ref/001.tif is where my reference image is located.

I get the following error:
_faststainnorm: error: argument --backend: invalid int value: 'torch'_

**Comment by andreped** [comment]
@ajr82 this is a silly bug. I had chosen the wrong type for a variable.

I have added a fix for it [here](https://github.com/andreped/fast-stain-normalization/commit/d88e550a741e54521c987c6bf3d5889d7f7f03e3). Try reinstalling and let me know how it went :]

**Comment by andreped** [comment]
I setup some unit tests for assessing that this works across multiple python versions and operating systems. Seems to work for both single and batch mode. You can see the build history [here](https://github.com/andreped/fast-stain-normalization/actions/runs/1995967978).

Then I believe this issue has been solved. Let me know if it worked for you or if you have any other issues. 

For new issues, please, create a new issue.

**Comment by ajr82** [comment]
Thank you very much! I tried it out and it works well now.
