### ISSUE TITLE
Image format not supported

### ISSUE THREAD

**Issue by fnurkinali** [andreped/fast-stain-normalization#5]
Hello!

My input is a folder with png images, but I am getting image format not supported error when I am running __main__.py. What is the reason and how can I solve this issue?

Thank you.

**Comment by andreped** [comment]
Most likely you are providing paths to the image reader which does not exist. We use `opencv` for reading images and it has the confusing error message of giving the same error for 1) attempting to read an unsupported image type and 2) attempting to read a path that does not exist (see [here](https://github.com/andreped/fast-stain-normalization/blob/main/source/__main__.py#L72) for where it most likely fails).

Regarding conversion, see [here](https://github.com/andreped/fast-stain-normalization/blob/main/.github/workflows/build.yml#L48) for how to convert the images. I assume that the PNG images all lie in the same folder and you provide the full path to the folder of images you wish to apply stain normalization on.

Also, is it the target image or the images you wish to convert it fails to read? In your error prompt it should say whether the error was at line 72 or 73 (see [here](https://github.com/andreped/fast-stain-normalization/blob/main/source/__main__.py#L72)).

**Comment by andreped** [comment]
Closing this issue as it appears to be inactive.

If you are still having issues, please, let me know and I can address it.
